name: Quality

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: microsoft
          java-version: 11
          cache: gradle
      - run: |
          set -x

          ./gradlew --no-daemon jar
